### PR TITLE
Add a GitHub Action to build the server.

### PR DESCRIPTION
**Pull request by bryanveloso**
This attempts to run CI using GitHub Actions rather than Travis CI. We can theoretically mimic our docker-compose layout this way.

### CODE REVIEW

**Comment by vito** [comment]
@bryanveloso Still carrying the RO torch, eh? 😆

...I was actually just researching the state of things a week ago. The nostalgia is too strong.

**Comment by bryanveloso** [comment]
LOL! That urge always comes back. Always. (I was surprised how many stars Aliter has.) Good to hear from you friend. :)

**Comment by vito** [comment]
Likewise! Hope you've been well. Man, Aliter was so fun to work on. Wish I got to work with Erlang more. I still remember all the reverse-engineering it took, and implementing something and having it immediately work without restarting the server or client.

**Comment by bryanveloso** [comment]
Well if you're ever interested in collaborating again, you know where to find me. :)

**Pull request merged**
